import { Entity } from '../models/space';

const CBU_REGEX = /^[0-9]{22}$/;

export const banks: Entity[] = [
  {
    color: '#007894',
    icon: 'nacion',
    value: 'NACION',
    label: 'Nacion',
    validationRegex: CBU_REGEX,
    defaultTags: [],
  },
  {
    color: '#e60000',
    icon: 'santander',
    value: 'SANTANDER',
    label: 'Santander',
    validationRegex: CBU_REGEX,
    defaultTags: [],
  },
  {
    color: '#f7931a',
    icon: 'galicia',
    value: 'GALICIA',
    label: 'Galicia',
    validationRegex: CBU_REGEX,
    defaultTags: [],
  },
  {
    color: '#1e3096',
    icon: 'bbva',
    value: 'BBVA',
    label: 'BBVA',
    validationRegex: CBU_REGEX,
    defaultTags: [],
  },
  {
    color: '#003057',
    icon: 'macro',
    value: 'MACRO',
    label: 'Macro',
    validationRegex: CBU_REGEX,
    defaultTags: [],
  },
  {
    color: '#db0011',
    icon: 'hsbc',
    value: 'HSBC',
    label: 'Hsbc',
    validationRegex: CBU_REGEX,
    defaultTags: [],
  },
  {
    color: '#4caf50',
    icon: 'itau',
    value: 'ITAU',
    label: 'Itau',
    validationRegex: CBU_REGEX,
    defaultTags: [],
  },
  {
    color: '#673ab7',
    icon: 'ciudad',
    value: 'CIUDAD',
    label: 'Ciudad',
    validationRegex: CBU_REGEX,
    defaultTags: [],
  },
  {
    color: '#8b0000',
    icon: 'brubank',
    value: 'BRUBANK',
    label: 'Brubank',
    validationRegex: CBU_REGEX,
    defaultTags: [],
  },
  {
    color: '#db0011',
    icon: 'icbc',
    value: 'ICBC',
    label: 'ICBC',
    validationRegex: CBU_REGEX,
    defaultTags: [],
  },
  {
    color: '#003057',
    icon: 'ccb',
    value: 'CCB',
    label: 'China Construction Bank',
    validationRegex: CBU_REGEX,
    defaultTags: [],
  },
  {
    color: '#4caf50',
    icon: 'abc',
    value: 'ABC',
    label: 'Agricultural Bank of China',
    validationRegex: CBU_REGEX,
    defaultTags: [],
  },
] as const;
